package com.mycompany.library_management_system;
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

/**
 *
 * @author youss
 */
public class CheckOutHistoryForm extends javax.swing.JFrame {
    private PatronForm patronform;
    private Patron patron;
    /**
     * Creates new form CheckOutHistory
     */
    public CheckOutHistoryForm() {
        initComponents();
    }
    
    public CheckOutHistoryForm(PatronForm patronform,Patron patron) {
        initComponents();
        this.patronform = patronform;
        this.patron = patron;
        ArrayList<String> fieldNames = new ArrayList<>();
        fieldNames.add("Book Id ");
        fieldNames.add("Title");
        fieldNames.add("Author");
        fieldNames.add("Publication Year");
        fieldNames.add("Category");
        fieldNames.add("Status");
        fieldNames.add("Checkout Date");
        
        ArrayList<CheckedoutHistory> checkedoutHistory = new ArrayList<>(this.patron.GetCheckedoutHistory());

        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(checkedoutHistory.size(), fieldNames.size(), 10, 20)); // ترتيب أفقي مع مسافات
        for(var book : checkedoutHistory )
        {
            for (String fieldName : fieldNames) {
                JLabel label = new JLabel(fieldName + ":");
                panel.add(label);

                JTextField textField = new JTextField(10); // الطول الافتراضي 10
                
                switch (fieldName) {
                    case "Book Id ":
                        textField.setText(book.getBook().getId());
                        break;
                    case "Title":
                        textField.setText(book.getBook().getTitle());
                        break;
                    case "Author":
                        textField.setText(book.getBook().getAuthor());
                        break;
                    case "Publication Year":
                        textField.setText(String.valueOf(book.getBook().getpublicationyear()));
                        break;
                    case "Category":
                        textField.setText(book.getBook().getCategory());
                        break;
                    case "Status":
                        textField.setText(book.getBook().getstatus() ? "Available" : "checked out");
                        break;
                    case "Checkout Date":
                        textField.setText(book.getDate()+"");
                        break;
                }

                panel.add(textField);

            }
            
        }
        // إضافة اللوحة إلى إطار (JFrame)
        getContentPane().add(panel, BorderLayout.CENTER); // تحديد الموضع داخل الإطار (وسط الشاشة)
        
        // إعادة ترتيب مكونات الإطار لعرض التغييرات
        revalidate();
        repaint();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Check out History");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 506, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(433, 433, 433))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(544, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.patronform.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOutHistoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOutHistoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOutHistoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOutHistoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOutHistoryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
